# Numpy Arrays

In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [4]:
import numpy as np

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
arr = np.array(my_list)

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_mat)    # 2디멘션 가능

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(0,11)   # arange([start,] stop[, step,], dtype=None)
                  # 11은 포함안됨

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.arange(0,11,2)   # step 포함

array([ 0,  2,  4,  6,  8, 10])

In [16]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [21]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [24]:
np.linspace(start = 0, stop = 5, num = 10)    # 0에서 5까지의 거리를 10개의 포인트로 나눠줌. 이건 1-D array 임

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [25]:
np.eye(4)   # 단위 행렬 = identity matrix

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [27]:
np.random.rand()   # 0-1 의 uniform distribution (정규 분포 아님)

0.27575550719160236

In [30]:
np.random.rand(5,5)

array([[ 0.56638007,  0.14241312,  0.06538426,  0.72496779,  0.63134708],
       [ 0.96263492,  0.35385955,  0.31664591,  0.13017851,  0.71570045],
       [ 0.51441381,  0.58375721,  0.01945336,  0.79748462,  0.87625029],
       [ 0.23950716,  0.30033195,  0.35657809,  0.69786189,  0.21118037],
       [ 0.43298919,  0.06822347,  0.15848058,  0.47135451,  0.89920097]])

In [31]:
# normal distribution 또는 gausian distribution 쓰고 싶은경우

np.random.randn()

-1.6604619478753766

In [35]:
np.random.randn(4,4)

array([[-0.09980128,  0.88740287,  0.45495651, -0.15187799],
       [-0.86055658,  0.7187297 ,  0.46099584,  0.22773617],
       [-0.76610016, -0.55969299,  1.18123566,  0.80475642],
       [-0.01049258,  0.01480406,  1.25787458, -0.96581471]])

In [38]:
np.random.randint(1,100)   # randint(low, high=None, size=None, dtype='l')

                            # low is inclusive and high is exclusive 즉 1은 포함 100은 미포함

31

In [40]:
arrr = np.arange(25)
arrr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [43]:
ranarr = np.random.randint(low = 0, high = 50, size = 10)    # 0에서 50 사이의 10개의 넘버
ranarr

array([25,  5, 32, 30, 40, 16, 26, 15,  6,  4])

In [44]:
arrr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
ranarr.max()

40

In [47]:
ranarr.min()

4

In [50]:
ranarr

array([25,  5, 32, 30, 40, 16, 26, 15,  6,  4])

In [51]:
ranarr.argmax()    # 최대 숫자가 어디에있는지 찾는법

4

In [52]:
ranarr.argmin()

9

In [53]:
arrr.shape    # row,column 을 보여줌 지금은 1-D

(25,)

In [54]:
arrr = arrr.reshape(5,5)
arrr.shape

(5, 5)

In [55]:
arrr.dtype

dtype('int32')

In [56]:
from numpy.random import randint

In [57]:
randint(1,100)   # np.random.randint(1,100) 이거를 더 쉽게 쓰는거임

67